package com.mwee.bpm.oa.dao.entity;

public class ActUserEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_ID_USER.ID_
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_ID_USER.REV_
     *
     * @mbggenerated
     */
    private Integer rev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_ID_USER.FIRST_
     *
     * @mbggenerated
     */
    private String first;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_ID_USER.LAST_
     *
     * @mbggenerated
     */
    private String last;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_ID_USER.EMAIL_
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_ID_USER.PWD_
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_ID_USER.PICTURE_ID_
     *
     * @mbggenerated
     */
    private String pictureId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_ID_USER.ID_
     *
     * @return the value of ACT_ID_USER.ID_
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_ID_USER.ID_
     *
     * @param id the value for ACT_ID_USER.ID_
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_ID_USER.REV_
     *
     * @return the value of ACT_ID_USER.REV_
     *
     * @mbggenerated
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_ID_USER.REV_
     *
     * @param rev the value for ACT_ID_USER.REV_
     *
     * @mbggenerated
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_ID_USER.FIRST_
     *
     * @return the value of ACT_ID_USER.FIRST_
     *
     * @mbggenerated
     */
    public String getFirst() {
        return first;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_ID_USER.FIRST_
     *
     * @param first the value for ACT_ID_USER.FIRST_
     *
     * @mbggenerated
     */
    public void setFirst(String first) {
        this.first = first == null ? null : first.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_ID_USER.LAST_
     *
     * @return the value of ACT_ID_USER.LAST_
     *
     * @mbggenerated
     */
    public String getLast() {
        return last;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_ID_USER.LAST_
     *
     * @param last the value for ACT_ID_USER.LAST_
     *
     * @mbggenerated
     */
    public void setLast(String last) {
        this.last = last == null ? null : last.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_ID_USER.EMAIL_
     *
     * @return the value of ACT_ID_USER.EMAIL_
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_ID_USER.EMAIL_
     *
     * @param email the value for ACT_ID_USER.EMAIL_
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_ID_USER.PWD_
     *
     * @return the value of ACT_ID_USER.PWD_
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_ID_USER.PWD_
     *
     * @param pwd the value for ACT_ID_USER.PWD_
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_ID_USER.PICTURE_ID_
     *
     * @return the value of ACT_ID_USER.PICTURE_ID_
     *
     * @mbggenerated
     */
    public String getPictureId() {
        return pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_ID_USER.PICTURE_ID_
     *
     * @param pictureId the value for ACT_ID_USER.PICTURE_ID_
     *
     * @mbggenerated
     */
    public void setPictureId(String pictureId) {
        this.pictureId = pictureId == null ? null : pictureId.trim();
    }
}