package com.mwee.bpm.oa.dao.mapper;

import com.mwee.bpm.oa.dao.entity.ActUserEntity;

import com.github.pagehelper.Page;

import org.springframework.stereotype.Repository;

@Repository
public interface ActUserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_ID_USER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_ID_USER
     *
     * @mbggenerated
     */
    int insert(ActUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_ID_USER
     *
     * @mbggenerated
     */
    int insertSelective(ActUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_ID_USER
     *
     * @mbggenerated
     */
    ActUserEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_ID_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_ID_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActUserEntity record);

    Page<ActUserEntity> selectAll();
}